server:
  port: 7979

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    non-secure-port: ${PORT:7979}
  client:
    serviceUrl:
      defaultZone: http://localhost:8961/eureka/

management:
    endpoints:
      jmx:
        exposure:
          include: "*"
      web:
        exposure:
          include: "*"
    metrics:
      sensitive: false
    endpoint:
      health:
        show-details: always
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
