spring:
  security:
    user:
      name: hm
      password: hmpass
    basic:
      enabled: false
  zipkin:
    enabled: false
  datasource:
    schema: classpath:/zipkin.sql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_dev_platform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    initialize: true
    continueOnError: true
  sleuth:
      enabled: false
#zipkin:
#  storage:
#    type: mysql
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8961/eureka/
    registry-fetch-interval-seconds: 10

#zipkin:
#  storage:
#    type: mysql